name: Deploy to Docker Hub
on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches: [main]
    tags: ['**']
    paths-ignore: ['*.md']
  pull_request:
    branches: [main]
jobs:
  deploy:
    name: Build Docker image
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: single
            latest: true
            suffix: ''
          - target: parallel
            latest: false
            suffix: -parallel
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: csquareai/ml-default
          flavor: |
            latest=${{ matrix.latest }}
            prefix=
            suffix=${{ matrix.suffix }}
          tags: |
            type=schedule
            type=edge,branch=main
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern=${{ matrix.target }},suffix=''
            type=sha
      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          target: ${{ matrix.target }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
