name: Deploy to Docker Hub
on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches: [main]
    tags: ['**']
#    paths: [Dockerfile, .github/workflow/deploy.yaml]
  pull_request:
    branches:
      - 'main'
jobs:
  deploy:
    name: Build Docker image
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: base
            suffix: ''
          - target: parallel
            suffix: parallel
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: csquareai/ml-default
          tags: |
            type=schedule,suffix=${{ matrix.suffix }}
            type=ref,event=branch,suffix=${{ matrix.suffix }}
            type=ref,event=pr,suffix=${{ matrix.suffix }}
            type=semver,pattern={{version}},suffix=${{ matrix.suffix }}
            type=semver,pattern={{major}}.{{minor}},suffix=${{ matrix.suffix }}
            type=semver,pattern={{major}},suffix=${{ matrix.suffix }}
            type=sha,suffix=${{ matrix.suffix }}
      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          target: ${{ matrix.target }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
#          build-args: ${{ }}
          labels: ${{ steps.meta.outputs.labels }}