name: Deploy to Docker Hub
on:
  push:
    branches: [main]
    paths: [Dockerfile, .github/workflow/deploy.yaml]
jobs:
  deploy:
    name: Build Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build base
        run: |
          docker build \
            --tag=csquareai/ml-default:base \
            --target=base \
            --build-arg=build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg=commit_hash=${GITHUB_SHA::8} \
            --build-arg=version=$(jq -r .version package.json) \
            .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Push on Docker Hub
        run: docker push csquareai/ml-default:base
