name: Quality assessment
on:
  push:
    branches: [main]
jobs:
  format:
    name: Format with Prettier
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'
          registry-url: https://npm.pkg.github.com
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/node_modules/
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Run Prettier
        run: npm run format:check
